image: maven:3-jdk-8
cache:
  paths:
   - .m2/repository/
stages:
  - build
  - test
  - deploy
package:
  stage: build
  before_script:
    - echo "Job de empacotamento"
  script:
    - mvn clean package
    - ls -la
  artifacts:
    name: $CI_JOB_NAME
    paths:
     - target/**.jar
  only:
    - master
  tags:
    - js
deploy_dev:
  image: thulioqueiroz/debian9-ansible
  stage: deploy
  before_script:
    - apt-get update
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIV_KEY_DEV" >> ~/.ssh/id_rsa.pem
    - chmod 600 ~/.ssh/id_rsa.pem
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa.pem
  script:
    - ssh-keyscan -H $IP_SERVER_DEV >> ~/.ssh/known_hosts
    - ls -la target
    - ansible-playbook deploy.yml -i hosts
    - ssh $USER_SERVER_SSH@$IP_SERVER_DEV "ls -la && java -jar gs-spring-boot-0.1.0.jar &"
  dependencies:
    - package
  environment:
    name: dev
    url: http://$IP_SERVER_DEV
  only:
  - master
  tags:
    - js